import { Metadata } from "next";
import "swiper/css";
import "swiper/css/navigation";
import "swiper/css/pagination";
import "swiper/css/effect-coverflow";
import "../styles/global.css";
import RecoilRootWrapper from "./RecoilWrapper";
import QueryRootWrapper from "./TanstackQueryWrapper";
import { Navigation } from "../components/navigation/navigation";
import { QueryClient } from "@tanstack/react-query";

export const dynamic = "force-dynamic";
export const metadata: Metadata = {
  title: {
    template: "%s | Next Movies Website",
    default: "Next Movie !",
  },
  description: "Generated by Next.js",
  icons: {
    icon: "/favicon.png",
  },
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html>
      <body>
        <RecoilRootWrapper>
          <QueryRootWrapper>
            <Navigation />
            {children}
          </QueryRootWrapper>
        </RecoilRootWrapper>
      </body>
    </html>
  );
}
