name: Deploy to EC2

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "20.16"
      - name: Install dependencies
        run: npm ci
      - name: Build
        run: npm run build
      - name: Setup SSH Key
        env:
          EC2_SSH_PRIVATE_KEY: ${{ secrets.EC2_SSH_PRIVATE_KEY }}
        run: |
          mkdir -p ~/.ssh
          echo "$EC2_SSH_PRIVATE_KEY" > movie-app.pem
          chmod 600 movie-app.pem
          ssh-keyscan -H 3.34.31.241 >> ~/.ssh/known_hosts
      - name: Deploy to EC2
        run: |
          scp -i movie-app.pem -r build/* ec2-user@3.34.31.241:~/next-movie-app
          ssh -i movie-app.pem ec2-user@3.34.31.241 << 'EOF'
            cd ~/next-movie-app
            npm install
            npm ci
            pm2 delete all || true
            pm2 start "npm run start" --name "next-movie-app"
          EOF
